version: "3"
services:
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
        #ro means only container can read only
            - ./:/usr/src/app:ro
        env_file:
            - ./.env
        environment:
        #since it's all in same file we are in a docker network so we only need to use the name of the postgres service
            - DATABASE_HOSTNAME=postgres
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi  
        volumes:
            - postgres-db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: willsavoie@gmail.com
            PGADMIN_DEFAULT_PASSWORD: pass
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 15432:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
volumes:
    postgres-db:
    pgadmin:

