version: "3"
services:
    api:
        # build: .
        image: #wsav/fastapi
        depends_on:
            - postgres
        ports:
            - 80:8000
        environment:
        #since it's all in same file we are in a docker network so we only need to use the name of the postgres service
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}  
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:

